steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/unique-atom-441707-u1/repo-1:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/unique-atom-441707-u1/repo-1:latest']
images:
  - 'gcr.io/unique-atom-441707-u1/repo-1:latest'
